language: cpp 
compiler:
    - gcc
before_script:
    - sudo apt-get install g++
    - sudo apt-get install libsnappy-dev
    - wget https://gflags.googlecode.com/files/libgflags0_2.0-1_amd64.deb
    - sudo dpkg -i libgflags0_2.0-1_amd64.deb
    - wget https://gflags.googlecode.com/files/libgflags-dev_2.0-1_amd64.deb
    - sudo dpkg -i libgflags-dev_2.0-1_amd64.deb
    - sudo apt-get install -y zlib1g-dev
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update
    - sudo apt-get install gcc-4.8
    - sudo apt-get install g++-4.8
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 20
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 20
    - sudo update-alternatives --config gcc
    - sudo update-alternatives --config g++
    - cd servidor
    - mkdir build
script:
    - cd bibliotecas/gmock && cmake . && make && cd ../..
    - cd bibliotecas/rocksdb && make static_lib -j8 && cd ../..
    - cd build
    - cmake ..
    - make
    - cd tests
    - ./tests
notifications:   # Notificamos los resultados de los test por correo
    recipients:
        - mafvidal@gmail.com
    email:
        on_success: change
        on_failure: always
