sudo: false
language: cpp

matrix:
  include:
    - os: linux
      compiler: clang
      env: COMPILER=clang++-3.6
      addons:
         apt:
            sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.6']
            packages: ['clang-3.6', 'zlib1g-dev', 'libbz2-dev', 'libsnappy-dev']
    - os: osx
      compiler: clang

before_script:
    - if [ -n "${COMPILER}" ]; then CXX=${COMPILER}; fi
    - if [[ $(uname -s) == 'Darwin' ]]; then brew install gflags snappy; fi

# Lousy hack to disable use and testing of fallocate, which doesn't behave quite
# as EnvPosixTest::AllocateTest expects within the Travis OpenVZ environment.
script: OPT=-DTRAVIS V=1 make -j4 check && OPT=-DTRAVIS V=1 make clean jclean rocksdbjava jtest

notifications:
    email:
      - leveldb@fb.com
    webhooks:
      - https://buildtimetrend.herokuapp.com/travis
